### ISSUE TITLE
Add memory usage Gauge and Graphs

### ISSUE THREAD

**Issue by thiagomaia971** [spdermn02/TouchPortal_OpenHardwareMonitor_Plugin#17]

**Comment by spdermn02** [comment]
thanks for the enhancement request - I'll see what I can do.

**Comment by spdermn02** [comment]
committed a start to adding more graphs and gauges - not just for memory but for GPU memory, and cpu/gpu temp as well. I do need to figure out a way to configure this to be turned off just to prevent so much data being transferred if/when the user doesn't want it.

**Comment by spdermn02** [comment]
I'm working on rewritting this completely using Node.JS and completely different through process, so all hardware found by Open Hardware Monitor (or Libre Hardware Monitor) will create their own categorized states and be usable. So no more set list of data, it will be all dynamic and work for whatever your hardware config is. Release date is TBD though. need to prioritize it onto my free time list.
