### ISSUE TITLE
Intel i9 Temperatures not showing

### ISSUE THREAD

**Issue by GmanAtheist** [spdermn02/TouchPortal_OpenHardwareMonitor_Plugin#20]
Hi. I have managed to set all other values for GPU, mem, temp, usage. But can not get the CPU temp to show. Please help me with the string. MSI Carbon WiFi MB. Thanks

**Comment by GmanAtheist** [comment]
![bgAgsjZtSS](https://user-images.githubusercontent.com/5624207/134812477-e279bc58-1ead-4e47-afc7-e4d1ab2f8736.png)

**Comment by GmanAtheist** [comment]
![NVIDIA_Share_JEzYqIsZOy](https://user-images.githubusercontent.com/5624207/134812493-55765ed5-a3f5-43f0-ba62-10c321162a30.png)

**Comment by spdermn02** [comment]
Does it show in the Open Hardware Monitor software correctly?

**Comment by GmanAtheist** [comment]
> Does it show in the Open Hardware Monitor software correctly?

AH. Yeah. No. CPU temp not showing in the Hardware Monitor. My bad, I missed that check. Is there any other monitoring software that is compatible with Touch Portal hardware monitor?. Thanks for the reply.

**Comment by spdermn02** [comment]
I’m interested as to why it isn’t showing any temperatures honestly. I wonder if something changed with how that sensor is found and an update to OHM itself is needed. 

Currently OHM is the only hardware monitor i know of with a plugin to touch portal. I have the api info for HWInfo64 but haven’t had the time to rebuild an interface for it in the languages I know.

**Comment by GmanAtheist** [comment]
Thanks. Yeah, It would be great if a better sensor app can be used. I use Core temp v1.17.1, it shows all my cpu temperatures. If only it could work with Touch portal hardware monitor.

**Comment by spdermn02** [comment]
I'll add that to my list of things to research.

**Comment by GmanAtheist** [comment]
Great, Thanks.

**Comment by spdermn02** [comment]
I'm working on rewritting this completely using Node.JS and completely different through process, so all hardware found by Open Hardware Monitor (or Libre Hardware Monitor) will create their own categorized states and be usable. So no more set list of data, it will be all dynamic and work for whatever your hardware config is. Release date is TBD though. need to prioritize it onto my free time list.

hopefully that includes the i9 temps.

**Comment by GmanAtheist** [comment]
Awesome. Thanks for your hard work. Much appreciated. looking forward to the update.

**Comment by spdermn02** [comment]
Sorry this took - seemingly forever - https://github.com/spdermn02/TouchPortal-HardwareMonitor
new release that is completely rewritten and different - and should work better. check it out. I will suggest converting over to Libre Hardware Monitor instead as their development seems to be more active.
