### ISSUE TITLE
Version 6 isn't working

### ISSUE THREAD

**Issue by Isaac-Chow** [spdermn02/TouchPortal_OpenHardwareMonitor_Plugin#21]
Yes I know it says that version 6 is experimental and might not work.
For me, none of the blocks are showing up so I just keep using v5.

I wonder when will version 6 be out and functional.

(idk how to add labels)

**Comment by spdermn02** [comment]
i am rebuilding this plugin actually, so it will be completely rewritten as a Node.JS plugin and won't be backwards compatible.  I'm still working on it though. I need to update the readme that this is deprecated and a new version will be coming that is a complete rewrite.

**Comment by spdermn02** [comment]
https://github.com/spdermn02/TouchPortal-HardwareMonitor - updated plugin fully rewritten. Check it out.
